use_frameworks!
platform :ios, '10.0'

target 'StatefulCollectionView_Example' do
  pod 'StatefulCollectionView', :path => '../'

  target 'StatefulCollectionView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.1'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
